### ISSUE TITLE
Lesymap errors - problem with mask

### ISSUE THREAD

**Issue by WieTro** [dorianps/LESYMAP#26] opened 2020-10-28 20:30 UTC
Dear Dorian

We have been running analyses with Lesymap and we now wanted to restrict the analyses with a predefined mask (from the WFU Pickatlas) to certain ROIs. However, we keep getting error messages. 
We made sure that the mask image is binary and is in the same space as the lesion images (mask image was coregistered (resliced) with SPM). And according to one previous issue mentioned here we also copied the header information from one of the lesions for the mask (in Matlab). However, the analysis runs without any problem when we used a dummy mask (one of the lesions itself).
To test the analysis with mask we always set optimizeSparseness to false for the moment.
Please find the error output below. Would you have an idea what we do wrong?
Thank you very much in advance!
Best,
Wiebke

> rm (list = ls (all = TRUE) )
> library(LESYMAP)
> 
> lesydata_template = file.path(find.package('LESYMAP'),'extdata')
> lesydata = '/home/nadia/Documents/Gedächtnis/FACscores_mitSDTGohneinkl/'
> filenames = Sys.glob(file.path(lesydata, 'lesions', 'VOI_*.nii'))
> behavior = Sys.glob(file.path(lesydata, 'behavior', 'FAC2_mitSDTGohneinkl.txt'))
> mask=Sys.glob(file.path(lesydata, 'mask', 'Papez_circuit_resliced_headercopy.nii'))
> mask=thresholdImage(mask, 0.1, Inf)
> template = antsImageRead(Sys.glob(file.path(lesydata_template, 'template', 'ch2.nii.gz')))
> lsm = lesymap(filenames, behavior, mask, method = 'sccan', optimizeSparseness=FALSE)
10:33:07 Running LESYMAP 0.0.0.9221
10:33:07 Checking a few things...
10:33:07 Loading behavioral data... 113 scores found.
10:33:07 Filenames as input, checking lesion values on 1st image...
10:33:07 SCCAN method: ignoring patch, nperm, and multiple comparison...
10:33:07 Using predefined mask...
10:33:07 noPatch true - Patches will not be used...
10:33:07 Computing lesion matrix...  113x170063
10:33:10 Checking matrix values are binary 0/1...
10:33:10 Running analysis: sccan ... 
       Calling SCCAN with: 
            Components:		 1 
            Use ranks:		 1 
            Sparseness:		 0.045 
            Cluster threshold:	 150 
            Smooth sigma:	 0.4 
            Iterations:		 20 
            maxBased:		 FALSE 
            directionalSCCAN:	 TRUE 
            optimizeSparseness:	 FALSE 
            validateSparseness:	 FALSEError in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...) : 
  0 (non-NA) cases
> plot(template, lsm$stat.img, window.overlay = range(lsm$stat.img))
Error in plot.antsImage(template, lsm$stat.img, window.overlay = range(lsm$stat.img)) : 
  object 'lsm' not found
> save.lesymap(lsm, saveDir = "/home/nadia/Documents/Gedächtnis/FACscores_mitSDTGohneinkl/results")
Error in "callinfo" %in% names(lsm) : object 'lsm' not found

**Comment by dorianps** [comment] 2020-10-28 20:52
Seems like the issue is coming from the code around [here](https://github.com/dorianps/LESYMAP/blob/master/R/lsm_sccan.R#L204-L210).

When you say you verified the mask was correct, what do you mean? Can you use ITKsnap to:
1. Open the template
2. Overlay a lesion to make sure it falls where it should.
3. Overlay the WFU mask to make sure it falls where it should.

Itksnap uses the same engine to load and interpret imaging data as LSYMAP/ANTs.

**Comment by WieTro** [comment] 2020-10-28 21:27
Thank you for your quick reaction!
You are right, that with ITKsnap the WFU mask is indeed not visible if I add it on a template, while the lesion falls where it should!
We always checked with mricron and also in SPM with check reg by opening the template, a lesion and the mask and it always looked like they would be fine. And the mask had been coregistered (resliced) beforehand to a lesion. 
So how would be the correct way to get the mask from WFU pickatlas into the right space then, so that Lesymap and ITKsnap can read it? 
Thank you very much in advance!

**Comment by dorianps** [comment] 2020-10-28 21:43
The underlying problem is explained [here](https://github.com/ANTsX/ANTs/wiki/How-does-ANTs-handle-qform-and-sform-in-NIFTI-1-images%3F). I don't have a ready solution because I have not encountered the problem myself. But I think the ANTs devs may have better insight on how to rewrite the image with ITKbased tools. Try asking the ANTs [isses page](https://github.com/ANTsX/ANTs/issues).

**Comment by WieTro** [comment] 2020-11-01 19:36
Thank you for your help! We will get more familiar with ITK-based tools and check on the ANTs issues page.
Best, 
Wiebke

**Comment by WieTro** [comment] 2020-11-10 21:55
Hi Dorian
We have now reproduced the mask again and in the present version it works if we overlay the predefined mask and one of the lesions on a template with ITKsnap.
However, we keep getting errors with both methods, BMfast and sccan (see below).
Do you have any other advice for us? 
Thank you very much!


> rm (list = ls (all = TRUE) )
> library(LESYMAP)
>  
> lesydata_template = file.path(find.package('LESYMAP'),'extdata')
> lesydata = '/Users/wiebketrost/FileCloud/Team Folders/Psychologie/20200528 Laesionsanalyse/Analysen/Lesymap/LESYMAP_test/AVLGT'
> filenames = Sys.glob(file.path(lesydata, 'lesions', 'VOI_*.nii'))
> behavior = Sys.glob(file.path(lesydata, 'behavior', 'AVLGT15_dummy.txt'))
> mask = Sys.glob(file.path(lesydata, 'mask', 'rPapez_circuit_WFU_original.nii'))
> mask = thresholdImage(mask, 0.1, Inf)
> template = antsImageRead(Sys.glob(file.path(lesydata_template, 'template', 'ch2.nii.gz')))
> lsm = lesymap(filenames, behavior, mask, method = 'BMfast')
21:43:10 Running LESYMAP 0.0.0.9221
21:43:10 Checking a few things...
21:43:10 Loading behavioral data... 145 scores found.
21:43:11 Filenames as input, checking lesion values on 1st image...
21:43:12 Using predefined mask...
21:43:13 Computing unique patches...
21:43:25 Found 1836 patches in 139200 voxels - 75.8 times more voxels
21:43:25 Using existing lesion matrix...  145x1836
21:43:25 Checking matrix values are binary 0/1...
21:43:25 Running analysis: BMfast ...
error: mean(): object has no elements
Fehler in BMfast2(lesmat, behavior, computeDOF = !FWERperm) : 
  mean(): object has no elements
> 

> lsm = lesymap(filenames, behavior, mask, method = 'sccan', optimizeSparseness=FALSE)
21:45:27 Running LESYMAP 0.0.0.9221
21:45:27 Checking a few things...
21:45:27 Loading behavioral data... 145 scores found.
21:45:28 Filenames as input, checking lesion values on 1st image...
21:45:29 SCCAN method: ignoring patch, nperm, and multiple comparison...
21:45:29 Using predefined mask...
21:45:29 noPatch true - Patches will not be used...
21:45:30 Computing lesion matrix...  145x139200
21:45:39 Checking matrix values are binary 0/1...
21:45:40 Running analysis: sccan ... 
       Calling SCCAN with: 
            Components:		 1 
            Use ranks:		 1 
            Sparseness:		 0.045 
            Cluster threshold:	 150 
            Smooth sigma:	 0.4 
            Iterations:		 20 
            maxBased:		 FALSE 
            directionalSCCAN:	 TRUE 
            optimizeSparseness:	 FALSE 
            validateSparseness:	 FALSEFehler in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...) : 
  0 (non-NA) cases
> 

> imi = antsImageRead(Sys.glob(file.path(lesydata, 'mask', 'rPapez_circuit_WFU_original.nii')))
> template = antsImageRead(Sys.glob(file.path(lesydata_template, 'template', 'ch2.nii.gz')))
> 
> plot(template, imi)
NULL

![Bildschirmfoto 2020-11-10 um 22 46 33](https://user-images.githubusercontent.com/65403056/98738230-ae8e3d00-23a7-11eb-8488-65ec63038c0e.png)

**Comment by dorianps** [comment] 2020-11-10 22:17
Your pictures looks from MRIcron. The options I see for you are:

1. Open the template in ITKsnap, then open a new ITKsnap with the mask.
They should be in sync and you can move around to see if the mask falls
where it should.
2. Send here the mask and the template so I can try it out.
3. (more complex) Check the headers of the two files with ANTs
(ImageHeader) or other software that can read nifti headers.

Hopefully this is a small error that can be fixed on your end.

**Comment by WieTro** [comment] 2020-11-11 07:40
Hi Dorian

Thank you for your reply.
I checked in ITKsnap opened twice with the template ch2.nii and our mask and it looks ok.
![Bildschirmfoto 2020-11-11 um 08 24 57](https://user-images.githubusercontent.com/65403056/98782527-6ea37600-23f8-11eb-95d9-f9ba2faa5993.png)

For point 2 I send here the template and our (dummy working) mask as a .zip, plus one lesion for which the analysis worked when we used it as mask.

[ch2.nii.gz](https://github.com/dorianps/LESYMAP/files/5522546/ch2.nii.gz)
[rPapez_circuit_WFU_original.nii.zip](https://github.com/dorianps/LESYMAP/files/5522549/rPapez_circuit_WFU_original.nii.zip)
[VOI_003.nii.zip](https://github.com/dorianps/LESYMAP/files/5522565/VOI_003.nii.zip)


For point 3 I will try to check the header information.
Thank you for your help!

**Comment by dorianps** [comment] 2020-11-11 14:24
Without even looking at the mask, I think I understand what might be going on in your case. Your custom mask probably includes voxels with no lesion at all. Statistics cannot run on those voxels. The mask created by lesymap falls only on voxels where there are lesions (be default on 10% of the patients).

You can only run stats on the intersection of the two masks, the one you want and the one lesymap computes by default. To intersect, you can simply multiply the masks.

Does it make sense?

**Comment by WieTro** [comment] 2020-11-11 15:19
Yes, that could be the case indeed. But this is probably not such a rare case that a mask does not include in every voxel at least lesions for 10% of the participants? We actually somehow supposed that the lesymap procedure would take that into account when an additional mask is included.
So you recommend to build beforehand an intersection between the predefined mask and a mask that includes lesioned voxel of least 10% of the participants if I understand you right? Would you do this 'by hand' or is there a way to get this default mask somehow via lesymap?
Thank you very much!

**Comment by dorianps** [comment] 2020-11-11 16:05
@WieTro  I thought about it, but I think LESYMAP should not interfere with the mask provided by the user to make a decision on cropping to voxels with 10% lesions only. It may also be misleading for users who are thinking they are analyzing every voxel in their mask input and lesymap doing its own thing. The mask argument is there for expert users who know what they need, and honestly was placed there at first only to save computational time by having the user provide a lesymap-generated mask without needing to recompute it each time you run the analyses. Adding more checks is possible and easy, but it would take to much computational time to check if voxels have enough statistical variance. It is not worth putting every user by default into more added time during analyses.

It is very simple to create the intersection mask in R:
```
wfuMask = antsImageRead(/PATH/TO/MASK)
lesymapMask = # this is returned by running a first lsm call, I think in lsm$mask

intersectMask = wfuMask * lesymapMask
```
I have not tried the code, so debug a bit yourself if it's not working right away.

**Closed** 2021-05-06 14:03 UTC
